#!/bin/bash -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( cd "$DIR"/../.. && pwd )"

. "$ROOT_DIR/init.sh"

S3_PATH="$S3_BUCKET/safari/"

cat "$BUILD_DIR/update.plist"
echo "Uploading..."
sleep 3
aws --profile first-mention-deploy s3 cp "$BUILD_DIR/update.plist" s3://${S3_PATH}update.plist
