#!/bin/bash
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( cd "$DIR"/../.. && pwd )"

. "$ROOT_DIR/init.sh"

rm -f "$BUILD_DIR"/*.xpi
VERSION="$( cat "$BUILD_DIR/firefox/manifest.json" | jq -r .version )"
echo "Signing $VERSION"
sleep 3
WEB_EXT_API_KEY=$AMO_API_KEY WEB_EXT_API_SECRET=$AMO_API_SECRET web-ext sign -s "$BUILD_DIR/firefox" -a "$BUILD_DIR"
